rules:
    # General lints
    avoid_print: true # Use a logging package instead of print
    prefer_const_constructors: true # Prefer using const constructors
    unnecessary_null_checks: true # Avoid unnecessary null checks
    use_full_hex_values_for_flutter_colors: true # Enforce full 8-digit hex values for colors
    sort_constructors_first: true # Keep constructors at the top of the class
    
    # Formatting and style
    always_put_required_named_parameters_first: true # Required parameters should come first
    use_late_for_private_fields_with_initializers: true # Use late for private fields with initializers
    prefer_single_quotes: true # Use single quotes for strings
    lines_longer_than_80_chars: false # Allow longer lines if necessary
    prefer_typing_uninitialized_variables: true # Explicit typing is preferred

    # Best practices
    prefer_final_fields: true # Prefer using final for fields when possible
    avoid_returning_null: true # Avoid returning null in non-nullable contexts
    require_trailing_commas: true # Require trailing commas where applicable
    avoid_unnecessary_containers: true # Avoid unnecessary usage of containers

    # Code readability
    omit_local_variable_types: false # Enforce explicit typing for readability
    always_specify_types: true # Always specify types for variables and fields
    
    annotate_overrides: true # Annotate overridden methods
